name: Docker build -> push -> deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6 
      
    - name: Setup java
      uses: actions/checkout@v6
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
      
    - name: Build Jar
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests
      
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Create docker iamge 
      run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-ci-cd-pipeline . #  Dot for choosing the current working-directory: for dockerfile

    - name: Push Image to docker hub
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-ci-cd-pipeline

    - name: SSH and Deploy to EC2 instance
      uses: appleboy/ssh-action@v1
      with:
        host:  ${{ secrets.EC2_HOST}}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop ci-cd-pipeline || true
          docker rm ci-cd-pipeline || true
          docker pull  ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-ci-cd-pipeline
          docker run -d --name ci-cd-pipeline -p 8081:8081  ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-ci-cd-pipeline
        



















      
